/** Shared types for the GitHub Intelligence module. */

export interface RepoOwner {
  login: string;
  avatarUrl: string;
  htmlUrl: string;
}

export interface RepoMetadata {
  name: string;
  fullName: string;
  owner: RepoOwner;
  description: string | null;
  htmlUrl: string;
  homepage: string | null;
  stars: number;
  forks: number;
  watchers: number;
  openIssues: number;
  language: string | null;
  license: string | null;
  defaultBranch: string;
  topics: string[];
  isPrivate: boolean;
  isArchived: boolean;
  isFork: boolean;
  createdAt: string;
  updatedAt: string;
  pushedAt: string;
  sizeKb: number;
}

export interface TechStackItem {
  id: string;
  label: string;
  category: 'language' | 'framework' | 'package-manager' | 'infra' | 'tooling';
  detectedFrom: string;
}

export interface TreeNode {
  name: string;
  path: string;
  type: 'file' | 'dir';
  children?: TreeNode[];
}

/**
 * Deterministic, non-AI signals derived directly from the repository's file
 * tree. This is the "ground truth" the AI reasoning layer is given so it
 * reasons over real repo facts instead of guessing.
 */
export interface RepoSignals {
  hasReadme: boolean;
  hasLicense: boolean;
  hasTests: boolean;
  hasCI: boolean;
  hasDocker: boolean;
  hasLinting: boolean;
  hasFormatting: boolean;
  hasTypeScript: boolean;
  hasEnvExample: boolean;
  hasContributingGuide: boolean;
  hasIaC: boolean;
  testFrameworks: string[];
  ciProviders: string[];
}

export type ArchitectureLayerId =
  | 'frontend'
  | 'backend'
  | 'database'
  | 'apis'
  | 'authentication'
  | 'deployment';

export interface ArchitectureLayer {
  layer: ArchitectureLayerId;
  detected: boolean;
  summary: string;
}

export interface RepoScoreBreakdown {
  architecture: number;
  maintainability: number;
  documentation: number;
  security: number;
  testing: number;
  overall: number;
}

/** Beginner / Intermediate / Advanced call, plus the reasoning behind it. */
export interface EngineeringMaturityAssessment {
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  reasoning: string;
}

/** A qualitative rating (e.g. "Low" / "Moderate" / "High") with supporting reasoning. */
export interface QualitativeAssessment {
  rating: string;
  reasoning: string;
}

/** One entry in the ranked, highest-impact-first improvement list. */
export interface RankedImprovement {
  /** 1 = highest priority. */
  priority: number;
  title: string;
  impact: string;
}

export interface AIInsights {
  /** 'ai' when generated by the LLM, 'heuristic' when produced by the deterministic fallback. */
  source: 'ai' | 'heuristic';
  summary: string;
  architecture: ArchitectureLayer[];
  strengths: string[];
  weaknesses: string[];
  codeQuality: string[];
  missingPractices: string[];
  scores: RepoScoreBreakdown;
  suggestions: string[];
  recruiterImpression: string;
  resumeBullets: string[];

  /** Overall engineering maturity call (Beginner / Intermediate / Advanced) with reasoning. */
  engineeringMaturity: EngineeringMaturityAssessment;
  /** Architecture quality rating with reasoning grounded in the detected structure. */
  architectureQuality: QualitativeAssessment;
  /** How well the project's design would hold up under growth (traffic, data, team size). */
  scalabilityAssessment: QualitativeAssessment;
  /** How easy the codebase would be to maintain, extend, and onboard new engineers into. */
  maintainabilityAssessment: QualitativeAssessment;
  /** Security-relevant observations based only on detected evidence (never speculative vulnerabilities). */
  securityObservations: string[];
  /** How close the project is to being production-ready, with reasoning. */
  productionReadiness: QualitativeAssessment;
  /** Interview questions generated specifically from the detected architecture and tech stack. */
  interviewQuestions: string[];
  /** Top improvements, ranked highest-impact first (priority 1 = do this first). */
  topImprovements: RankedImprovement[];
}

export interface RepoAnalysis {
  metadata: RepoMetadata;
  techStack: TechStackItem[];
  tree: TreeNode[];
  truncated: boolean;
  fileCount: number;
  signals: RepoSignals;
  insights: AIInsights;
}

export interface AnalyzeErrorBody {
  error: string;
}
