/**
 * contracts/agent.contract.ts
 *
 * The single contract every AI agent in CareerOS implements, now and in the
 * future. Nothing in this file talks to a model provider — it only defines
 * shape. Providers, prompts, and reasoning are plugged in later behind this
 * same interface, which is the point: the orchestrator, workflows, and API
 * layer only ever code against `Agent<TInput, TOutput>`, never against a
 * specific agent's internals.
 */

import type { AgentId } from '../types/agent-id';

/** Every agent input is required to be traceable back to a candidate/run. */
export interface AgentExecutionContext {
  /** Unique id for this single agent run. Generated by the orchestrator. */
  executionId: string;
  /** Id of the workflow run this execution belongs to, if any. */
  workflowExecutionId?: string;
  /** The authenticated user this run is being performed for. */
  userId: string;
  /** ISO timestamp the execution started. */
  startedAt: string;
  /** Arbitrary trace metadata (feature flag states, request id, etc). */
  trace?: Record<string, unknown>;
}

export type AgentStatus = 'not_implemented' | 'success' | 'partial' | 'failed';

/** Confidence is always surfaced explicitly rather than implied. */
export interface AgentConfidence {
  /** 0–1. Agents that are not yet implemented must return 0. */
  score: number;
  /** Short human-readable reason for the score. */
  rationale: string;
}

export interface AgentCostEstimate {
  /** Estimated provider tokens, input + output. 0 until a provider exists. */
  estimatedTokens: number;
  /** Estimated USD cost. 0 until a provider exists. */
  estimatedUsd: number;
}

export interface AgentMetadata {
  agentId: AgentId;
  /** Semver of the agent implementation, independent of prompt version. */
  version: string;
  /** Semver of the prompt template in /prompts, once one exists. */
  promptVersion: string | null;
  /** Model/provider that produced the result. Null until wired up. */
  provider: string | null;
  model: string | null;
}

/** Uniform envelope every agent returns. Agents never return plain text. */
export interface AgentResult<TOutput> {
  status: AgentStatus;
  /** Present when status is 'success' or 'partial'. */
  output: TOutput | null;
  confidence: AgentConfidence;
  cost: AgentCostEstimate;
  /** Wall-clock milliseconds spent inside run(). */
  executionTimeMs: number;
  metadata: AgentMetadata;
  /** Populated when status is 'failed' or 'partial'. */
  errors: AgentError[];
}

export type AgentErrorCode =
  | 'NOT_IMPLEMENTED'
  | 'VALIDATION_ERROR'
  | 'PROVIDER_ERROR'
  | 'TIMEOUT'
  | 'UNKNOWN';

export interface AgentError {
  code: AgentErrorCode;
  message: string;
  details?: Record<string, unknown>;
}

/**
 * The standard shape every agent module exports as its default implementation.
 * TInput/TOutput are defined per-agent in that agent's `types.ts` and should
 * reference shared domain types from /contracts wherever possible instead of
 * redeclaring fields.
 */
export interface Agent<TInput, TOutput> {
  readonly id: AgentId;

  /** Returns validation errors, or an empty array when input is valid. Never throws. */
  validateInput(input: TInput): AgentError[];

  /** Executes the agent. Placeholder agents return a NOT_IMPLEMENTED result without throwing. */
  run(input: TInput, context: AgentExecutionContext): Promise<AgentResult<TOutput>>;

  /** Sanity-checks a produced output before it is handed back to the orchestrator. */
  validateOutput(output: TOutput | null): AgentError[];

  /** Static confidence policy for this agent (may be overridden per-run inside run()). */
  confidence(): AgentConfidence;

  /** Static identity/versioning info for this agent. */
  metadata(): AgentMetadata;

  /** Semver of this agent implementation. Shorthand over metadata().version. */
  version(): string;

  /** Estimated cost of running this agent against a given input. */
  costEstimate(input: TInput): AgentCostEstimate;

  /** Wall-clock ms of the most recently completed run(), or null before any run. */
  executionTime(): number | null;
}
